* Step  1 
1. Imported Needed Libraries

In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.metrics import r2_score , mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

* Step 2 
1. Loaded Data 
2. Show Data 5 First 
3. Show Information For Data
4. Show Data Describe
5. Divided Data For (Input Data & Output Data) 

In [7]:
data = pd.read_csv('D:\\Array Diploma\\Data\\Data1.csv')
print('\t\t The First Data Is : \n',data.head(5))
print('***'*30)
print('\t\t The Data Information Is : \n',data.info())
print('***'*30)
print('\t\t The Data Describe Is : \n',data.describe())
print('***'*30)
x_data = data.iloc[:,:-1].values
y_data = data.iloc[:,-1].values

		 The First Data Is : 
       AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90
******************************************************************************************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9568 entries, 0 to 9567
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AT      9568 non-null   float64
 1   V       9568 non-null   float64
 2   AP      9568 non-null   float64
 3   RH      9568 non-null   float64
 4   PE      9568 non-null   float64
dtypes: float64(5)
memory usage: 373.9 KB
		 The Data Information Is : 
 None
******************************************************************************************
		 The Data Describe Is : 
                 AT            V           AP           RH           PE
count  9568

* Step 3 
1. Splitting Data For Training Data & Test Data 
2. Show Information For Training Data & Test Data

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x_data,y_data,test_size=0.2,random_state=0)
print('\t\t The First 5 Rows From X Training Data Is : \n',x_train)
print('***'*30)
print('\t\t The First 5 Rows From X Test Data Is : \n',x_test)
print('***'*30)
print('\t\t The First 5 Rows From Y Training Data Is : \n',y_train)
print('***'*30)
print('\t\t The First 5 Rows From Y Test Data Is : \n',y_test)
print('***'*30)

		 The First 5 Rows From X Training Data Is : 
 [[  11.22   43.13 1017.24   80.9 ]
 [  13.67   54.3  1015.92   75.42]
 [  32.84   77.95 1014.68   45.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]
******************************************************************************************
		 The First 5 Rows From X Test Data Is : 
 [[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]
******************************************************************************************
		 The First 5 Rows From Y Training Data Is : 
 [473.93 467.87 431.97 ... 459.01 462.72 428.12]
******************************************************************************************
		 The First 5 Rows From Y Test Data Is : 
 [431.23 460.01 461.14 ... 473.26 438.   463.28]
***************

* Step  4
1. Training Multiple Linear Regression Model On The Training Set

In [11]:
Regressor = LinearRegression()
Regressor.fit(x_train,y_train)

LinearRegression()

* Step 6 
1. Predicting The Test Result

In [12]:
y_pred=Regressor.predict(x_test)
np.set_printoptions(precision=2) # 
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]


* Step 7 
1. Evaluating The Model Performance

In [13]:
r = r2_score(y_test,y_pred)*100
r

93.25315554761303