## 1- write a function that adds two vectors together

In [24]:
#First Program 
import numpy as np            
def func_sum(num1,num2):
    print('\t\t The Values Of Vector Num1 \n',num1)
    print('**'*25)
    print('\t\t The Values Of Vector Num2 \n',num2)
    print('**'*25)
    result1=[]
    for i in range(len(num1)):
        result1.append(num1[i]+num2[i])
    return result1 
print('\t\t The Final Add Vetors Is \n ', func_sum([1, 2, 3], [4, 5, 6]))
print('**'*20)
#================================================================================
#Second Program 
def func_add(num3,num4):
    assert len(num3) == len(num4)
    return [num3_i + num4_i for num3_i, num4_i in zip(num3, num4)]
assert func_add([1, 2, 3], [4, 5, 6]) == [5, 7, 9]

		 The Values Of Vector Num1 
 [1, 2, 3]
**************************************************
		 The Values Of Vector Num2 
 [4, 5, 6]
**************************************************
		 The Final Add Vetors Is 
  [5, 7, 9]
****************************************


## 2- Write a function that multiplies a scalar and a vector

In [3]:
def func_mult(num5,num6):
    print('The Number Of Scalar Is ==> ',num5)
    print('The Vector Num6 Is ==> ',num6)
    result = []
    for i in num6:
        #result.append(num5 * i)
        result.append(np.dot(num5,i))    
    return result 
print('The Scalar Multiply Is (2,[2,4,6]) ==> ',func_mult(2,[2,4,6]))
print('=========================================================================')
def func_mult1(num1,num2):
    print('The Scalar Number For Num1 Is ==> ',num1)
    print('The Vector Num2 Is ==> ',num2)
    return [np.dot(num1 , i) for i in num2]
print('The Final Result From Multiply Scalar With Vector (2,[2,4,6])==> ',func_mult1(2,[2,4,6]))

The Number Of Scalar Is ==>  2
The Vector Num6 Is ==>  [2, 4, 6]
The Scalar Multiply Is (2,[2,4,6]) ==>  [4, 8, 12]
The Scalar Number For Num1 Is ==>  2
The Vector Num2 Is ==>  [2, 4, 6]
The Final Result From Multiply Scalar With Vector (2,[2,4,6])==>  [4, 8, 12]


## 3-  Write a function that multiplies two vectors

In [4]:
def func_dot(var1,var2):
    assert len(var1)== len (var2)
    return np.sum(np.multiply(var1_i , var2_i) for var1_i , var2_i in zip (var1,var2))
print('The Final Result From Two Vectors ==> ',func_dot([1,2,3],[4,5,6]))

The Final Result From Two Vectors ==>  32


C:\Users\Alhou\AppData\Local\Temp\ipykernel_15492\2387247113.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  return np.sum(np.multiply(var1_i , var2_i) for var1_i , var2_i in zip (var1,var2))


## 4-  Write a function that takes a matrix and gives you its shape.

In [5]:
def func_shape(S):
    num_of_rows=len(S)
    num_of_cols=len(S[0]) if S else 0
    return num_of_rows,num_of_cols
print('The Shape Of Matrix[1,2,3],[4,5,6] By Using Function ==> ',func_shape([[1, 2, 3], [4, 5, 6]]))

The Shape Of Matrix[1,2,3],[4,5,6] By Using Function ==>  (2, 3)


## 5-  Write a function that adds two matrices

In [6]:
def func_add1(M1,M2):
    return [np.sum(M1_i,M2_i) for M1_i , M2_i in zip(M1,M2)]
def Add_Matrix(Matrix1,Matrix2):
    return list(np.add(Matrix1_i,Matrix2_i) for Matrix1_i ,Matrix2_i in zip(Matrix1,Matrix2))
A = [[1, 2, 3], [4, 5, 6]]
B = [[1, 2, 3], [4, 5, 6]]
print(Add_Matrix(A,B))

[array([2, 4, 6]), array([ 8, 10, 12])]


## 6 -  Write a function that multiply two matrices element-wise

In [15]:
def mult_element_wise(var1, var2):
     assert len(var1) == len(var2), "Vectors must be the same length"
     return list (np.multiply(var1_i,var2_i) for var1_i , var2_i in zip (var1,var2)) 
def matrix_mult_element_wise(A, B):
     print('\tThe Matrix A Is \n ',np.array(A))
     print('**'*30)
     print('\tThe Matrix B Is \n ',np.array(B))
     print('**'*30)
     c = []
     for i in range(len(A)):
         c.append(mult_element_wise(A[i], B[i]))
     return np.array(c)
A = [[1, 2, 3], [4, 5, 6]]
B = [[1, 2, 3], [4, 5, 6]]
print('\t\t The Final Matrix C ==> (A * B ) Is \n',matrix_mult_element_wise(A, B))


	The Matrix A Is 
  [[1 2 3]
 [4 5 6]]
************************************************************
	The Matrix B Is 
  [[1 2 3]
 [4 5 6]]
************************************************************
		 The Final Matrix C ==> (A * B ) Is 
 [[ 1  4  9]
 [16 25 36]]


## 7- Write a function that multiply a vector with a matrix

In [19]:
def dot(num1, num2):
    assert len(num1) == len(num2), "Vectors must be the same length"
    return np.sum(list(np.multiply(num1_i,num2_i) for num1_i,num2_i in zip(num1,num2)))
def matrix_mult_vector(A, b):
    print('\tThe Matrix A Is \n ',np.array(A))
    print('**'*30)
    print('\tThe Matrix B Is \n ',np.array(B))
    print('**'*30)
    c = []
    for i in range(len(A)):
         c.append(dot(A[i], b))
    return np.array(c)
A = [[1, 2], [3, 4], [5, 6]]
b = [0.5, 0.5]
print('The Final Matrix C ==> (A * B ) Is ==> ',matrix_mult_vector(A, b))

	The Matrix A Is 
  [[1 2]
 [3 4]
 [5 6]]
************************************************************
	The Matrix B Is 
  [[1 2 3]
 [4 5 6]]
************************************************************
The Final Matrix C ==> (A * B ) Is ==>  [1.5 3.5 5.5]


## 8-Write a function that multiplies a matrix by a scalar


In [9]:
def scaler_multiply(c, v):
    return [c * v_i for v_i in v]
def matrix_mult_scaler(A, b):
     c = []
     for i in range(len(A)):
         c.append(scaler_multiply(b, A[i]))
     return c
A = [[1, 2], [3, 4], [5, 6]]
b = 0.5
print(matrix_mult_scaler(A, b))

[[0.5, 1.0], [1.5, 2.0], [2.5, 3.0]]
